In [13]:
import numpy as np
import cv2
import os

In [3]:
img=cv2.imread("images/img4.png")
re_img=cv2.resize(img,(500,700))
cv2.imshow("Window",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
v=np.array([[1,2,3,1,2,3],[1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [7]:
np.hstack((v,v))   # horizontal join

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [8]:
np.vstack((v,v))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [5]:
img=cv2.imread("images/img4.png")
print(img) #RGB

[[[ 30  30  30]
  [ 30  30  30]
  [ 31  31  30]
  ...
  [ 31  31  29]
  [ 32  32  30]
  [ 32  32  30]]

 [[ 23  21  22]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [ 34  35  32]]

 [[ 41  39  38]
  [ 83  82  80]
  [102 102  99]
  ...
  [ 82  82  80]
  [ 59  59  57]
  [ 25  26  23]]

 ...

 [[ 56  44  32]
  [ 66  54  44]
  [ 76  64  55]
  ...
  [186 179 163]
  [121 114  98]
  [  0   0   0]]

 [[ 72  51  29]
  [ 78  57  35]
  [ 84  63  42]
  ...
  [190 170 148]
  [120 100  79]
  [ 17   0   0]]

 [[ 87  57  23]
  [ 88  57  25]
  [ 93  62  30]
  ...
  [165 133 100]
  [118  86  55]
  [ 53  21   0]]]


In [11]:
img=cv2.imread("images/img6.png")
re_img=cv2.resize(img,(300,500))
# h=np.hstack((re_img,re_img))  # Horizintal join
v=np.vstack((re_img,re_img))   # Vertical join
cv2.imshow("Window",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
img=cv2.imread("images/img6.png")
re_img=cv2.resize(img,(300,300))
h=np.hstack((re_img,re_img))  # Horizintal join
v=np.vstack((h,h))   # Vertical join
cv2.imshow("Window",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
list_name=os.listdir("images\\")
for name in list_name:
    path="images\\"
    img_name=path + "\\" + name
    img=cv2.imread(img_name)
    img=cv2.resize(img,(500,600))
    cv2.imshow("Window",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()